### ISSUE TITLE
Referencing external template for custom input type

### ISSUE THREAD

**Issue by pixelhijack** [json-schema-form/angular-schema-form#174]
Hi!
Question: how can I reference an external template file? 

I understand the ways you can extend Schema Form (1. adding a field, 2. decorators), but can't find how to reference path to any other .html template files that's not in the 'directives/decorators/bootstrap/' folder as angular-schema-form is nested deep in the project's bower_components folder. Relative path references don't seem to work (like '../../../scripts/feature/templates/checkbox.html'). Should they...?

**Comment by davidlgj** [comment]
Yes as @brian428 pre-compiling is a good way to go. Otherwise the path should be relative to where the page url is on the server, i.e. highly dependent on your setup. Which sucks when your doing a library that's why we pre-compile templates. This is actually more of a Angular issue, think of the paths as paths you would use in an `ng-include`.

You could also solve it by using a $http interceptor that "fixes" the urls so they match whatever server setup you have.

**Comment by stephenreid** [comment]
There are two different ways you may want to implement this:

1) A custom decorator (for the individual element)

You need to do step two, and write a new directive to replace sf-decorator.

2) A custom sf form (for the buttons, etc).

You will need to extend the mappings in your app.js with these new files and specify the types in your forms.json

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
