### ISSUE TITLE
Deleting array item in multi-item array copies deleted invalid value to another array item

### ISSUE THREAD

**Issue by jrothman** [json-schema-form/angular-schema-form#274]
In the demo array example: create two array items. leave the email field blank in the first array item and make an invalid email address in the second array item. When you delete the second array item, it automatically copies the erroneous email address to the first array item email field.

**Comment by yunicz** [comment]
+ 1 but it goes deeper
Open your console and visit this Fiddle http://jsfiddle.net/4et1su5h/3/

Step 1: Add new item called 1.
Step 2: Add new item called 12.
Step 3: Add new item called 123.
Step 4: Add new item called 1234.
So far so good.
Step 5: Change the first item (1) to 1234 so that an error message appears.
Step 6: Delete the last item so that the first one is unique again. But nothing happens. The array is not validated again once an item is removed and even if you click on the submit button which should trigger the valdiation of form nothing happens.

**Comment by Anthropic** [comment]
I believe this is fixed in the latest updates (alphas) for the eventual 1.0.0 release.

Please re-open if there are still issues in these versions.
