### ISSUE TITLE
Schema changes aren't handled correctly

### ISSUE THREAD

**Issue by aantipov** [json-schema-form/angular-schema-form#395]
I have 2 schemes and 1 form definition:
**Schema 1**:

```
{   
    "type": "object",
    "required" : ["name"],
    "properties": {
        "name": { "type": "string", "title": "First Name"}
    }
}
```

**Schema 2**:

```
{   
    "type": "object",
    "required" : ["name"],
    "properties": {
        "name": { "type": "string", "title": "My First Name",  "enum": ['Alex', 'Peter'],}
    }
}
```

**Form**:

```
[ 
    {"key": 'name', "htmlClass": "col-sm-12"}
]
```

Schema 1 is default, so default field type is text.
When I switch to Schema 2 the field aren't changed to select, it remains the same input[type=text].

I've made some research and found out, that
1. The field's scope has property `schemaForm` and its value has 2 properties `form` and `schema`
2. `schema`'s value corresponds to selected schema 2. That is OK.
3. `form`'s value contains info about the field, and this field's info contains info about the schema. But this schema info doesn't corresponds to current Schema 2, it corresponds to previous Schema 1. This is NOT OK.

**Comment by davidlgj** [comment]
They aren't watched deeply, you need to issue a `schemaFormRedraw` event, see docs here for more info: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#updating-form

**Comment by aantipov** [comment]
@davidlgj It didn't help. Actually I change schema object, not just its properties, so it should work without issuing `schemaFormRedraw` event.

**Comment by davidlgj** [comment]
I think I found the issue, If you supply a form definition with form objects those objects are then reused internally, for instance setting the `schema` attribute on them. This is what causes the problem. 

So as a workaround do an `angular.copy` of the form definition as well when you update the schema. 

I think we'll  need to add one internally as well. Both to form and schema since we modify them both when needed. Shouldn't be that much of a performance issue I hope :)

**Comment by aantipov** [comment]
ok, I'll try the workaround later. thanks

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
