### ISSUE TITLE
Helping building a question form with "other" option as answer

### ISSUE THREAD

**Issue by JobaDiniz** [json-schema-form/angular-schema-form#400]
Hi, I could configure angular-schema-form to build dynamic surveys... this is working:
- Questions with multiple options & multiple answers (checkboxes)
- Questions with multiple options & one answer (radio button)

However, most of the questions have a *text* option, like *"If none of above, answer here"*.
How can I build a question with multiple options, but one of the options should be presented with **input type="text"** rather than a **radio button** or **checkbox**?

*Example:*
![capturar](https://cloud.githubusercontent.com/assets/165290/7798714/db9dbf8c-02d3-11e5-8566-00de3e582989.PNG)

**Comment by Dervisevic** [comment]
This is kind of an conundrum, as ASF is JSON Schema based. Checkboxes have the type: array, and the input is type text, so they don't really go together. What you really need is oneOf. This is something we are working on for the 1.0 release. However, the current design for it would be a select, where you choose what is displayed, either the checkboxes or the other box. 

Maybe disregard the text above depending on how you want it. How i understand your problem is that you want the "if other please identify" to be a part of the array? So that you can choose multiple options and also specify other, that they are not mutually exclusive?

In that case an addon is the way to go, you base it on the checkboxes type but you always include a text input as well that will be append to the model array. This is the documentation on addons.

**Comment by JobaDiniz** [comment]
> So that you can choose multiple options and also specify other, that they are not mutually exclusive?
In that case, yes. It would be part of the array and user could select checkboxes and also type into the input.

But there is also a _mutually exclusive_ case, where _radio buttons_ will be presented and also the input:
![capturar](https://cloud.githubusercontent.com/assets/165290/7812571/db573bfa-0389-11e5-9e79-c1fcff607c13.PNG)

Where is the documentation of addons? Is it hard to implement such thing?

**Comment by Dervisevic** [comment]
Oh sorry! Looks like i forgot to post the link. https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md

I've made maybe 6-8 addons and in my experience it isn't that hard. The documentation is descent but if you have any questions pop into the gitter: https://gitter.im/Textalk/angular-schema-form

If you want to look at an existing addon you can check out the [colorpicker addon](https://github.com/Textalk/angular-schema-form-colorpicker). You can see all public addons at the bottom of http://schemaform.io

And here is the template for checkboxes: https://github.com/Textalk/angular-schema-form/blob/development/src/directives/decorators/bootstrap/checkboxes.html

**Comment by JobaDiniz** [comment]
Just to make sure I'm on the right track: I will have to implement some sort of `ng-if` to output either a _input type checkbox_ or _input type text_ in this [line of code](https://github.com/Textalk/angular-schema-form/blob/development/src/directives/decorators/bootstrap/checkboxes.html#L7-L13)?

**Comment by Dervisevic** [comment]
The problem with that would be that a input type text would result in a string and checkboxes are array. There are ways alternative ways to do it but i don't know any off the top of my head so I'll let @davidlgj answer further.

**Comment by davidlgj** [comment]
Hi @JobaDiniz, 
your sort of on the right track. That would be one way to do it, but you still need some custom directive that updates the model list by appending the value in the string.

**Comment by JobaDiniz** [comment]
I would replace [this code](https://github.com/Textalk/angular-schema-form/blob/development/src/directives/decorators/bootstrap/checkboxes.html#L5-L16) with: 

```
<div class="checkbox" ng-repeat="val in titleMapValues track by $index" >
    <label ng-if="!titleMapValues[$index].isText">
      <input type="checkbox"
             ng-disabled="form.readonly"
             sf-changed="form"
             class="{{form.fieldHtmlClass}}"
             ng-model="titleMapValues[$index]"
             name="{{form.key.slice(-1)[0]}}">
      <span ng-bind-html="form.titleMap[$index].name"></span>
    </label>

    <label ng-if="titleMapValues[$index].isText">
     <span ng-bind-html="form.titleMap[$index].name"></span>
      <input type="text"
             ng-disabled="form.readonly"
             sf-changed="form"
             class="{{form.fieldHtmlClass}}"
             ng-model="titleMapValues[$index]"
             name="{{form.key.slice(-1)[0]}}">
    </label>

  </div>
```
And when configuring the *form object*:
```
var form = [];
var questionModel = {
   key: 'questionIdKey',
   title: 'What is your first language?',
   disableSuccessState: true,
   type: 'customCheckboxes',
   titleMap: []
 };
questionModel.titleMap.push({
  value: '1',
  name: 'English',
  isText: false
});
questionModel.titleMap.push({
  value: '2',
  name: 'Portuguese',
  isText: false
});
questionModel.titleMap.push({
  value: '3',
  name: 'If other please identify',
  isText: true
});

form.push(questionModel);
```

Wouldn't `ng-model="titleMapValues[$index]"` work out of the box in my scenario?

**Comment by davidlgj** [comment]
I'm afraid not, the `titleMapValues` are booleans which index match the `form.titleMap` array. So you can't bind against it with an input. You need a custom directive on that input that adds the value to the model array, changes it when it changes and removes it when it's no longer needed.

**Comment by lucas-ribeiro** [comment]
I'm working with @JobaDiniz on this one. I was looking through the docs and I thought that maybe a nested schema with `type: "object"` could be the solution, so we could define two properties: "options" as an array (for checkboxes) and "text" as a string for the text answer. This way we would be able to get separate responses and maybe it would be easier to get a proper object in the answers object.

However it didn't work, because of an error thrown in `defaultFormDefinition()`. Here's what I did (this is the schema for a single question, not the full schema object):

```javascript
{
    type: 'object',
    title: question.Title,
    properties: {
        Options: {
            title: question.Title,
            type: 'array'
        },
        Text: {
            type: 'string',
            title: 'If other, please identify',
        }
    }
};
```

I may be getting this totally wrong, but even if it does not work in the current version, it may still be used as a suggestion.

**Comment by nicklasb** [comment]
Have you found a solution to this? As the issue has been inactive so long I am closing it.
Please re-open if you have more to add.
