### ISSUE TITLE
Backend validation w/o ngModelController

### ISSUE THREAD

**Issue by alanguir** [json-schema-form/angular-schema-form#449]
I'm stuck trying to invalidate form fields in schema form, and I'm also stuck using angualr 1.2, so don't have access to async validators or ngModelController. None of the docs seem to be getting me to where I'd like to go and being able to manually invalidate a field seems like it would be a basic or core features. 

My end goal is to create a confirm email field, where if given this form: 
```
{
   key: 'email',
},
{
   key: 'confirmEmail',
}
```
I want to invalidate the `confirmEmail` field if either field is edited and their values do not match. 

I've tried all manner of approaches:

 - async validators, b/c why not try?
 - manually set `$valid = false` on form (no effect)
 - return false from custom `validationMessage` function as per [the docs](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#taking-over-functions-as-validationmessages), also to no effect
  - manually update the validation patterns both in the form and schema for `confirmEmail` to simply match the `modelValue` of `emails` - still no effect despite calling both `$scope.$broadcast('schemaFormRedraw')` and `$scope.$broadcast('schemaFormValidate')`. It appears that ASF doesn't pick up on changes to that value. 

So - what am I missing and why is this seemingly simple thing so hard?The job is being done internally to test patterns and min/max lengths, and I just can't figure out how to hook in.

**Comment by nicklasb** [comment]
There are many things that are seemingly simple that are hard. :-)
The problem is that ASF if designed to work against a model, and you don't want to save both, right?
In this case one could use a template, or for the community, create an addon for that case. 
Actually it seems like a valid idea for an add-on. 
There is a guide and examples on how to create add-ons here: https://github.com/json-schema-form/angular-schema-form-add-ons
Also a yeoman generator: https://github.com/json-schema-form/generator-angular-schema-form-add-on

**Comment by Anthropic** [comment]
As this is an old issue, please re-open if you do not feel the question has been answered sufficiently.
