### ISSUE TITLE
How to handle multiple languages

### ISSUE THREAD

**Issue by leader80** [json-schema-form/angular-schema-form#460]
Hi guys,

how do you handle multiple language forms?

Cheers
L

**Comment by Dervisevic** [comment]
You can always use a different form definition for the different languages. You can specify title, description etc there, and you can even override the validation messages.

**Comment by leader80** [comment]
You mean same Form different Schema?
Is it not possible to define a key and then translate via translation service? it would be great if you have language files, to avoid rewriting the schema multiple time.

**Comment by Dervisevic** [comment]
No, i meant form, the schema defines the data, the form defines the layout. For example, here is a schema with one property, and then in the form i do three fields for the same one (Instead of showing with different forms) http://schemaform.io/examples/bootstrap-example.html#/1243d961add347f9135b

The method above is simple, The way we do it is use [Jed](https://slexaxton.github.io/Jed/) (gettext) for translating and pop that into a form. Here's an example: https://git.diversity.io/textalk-webshop-native-components/tws-aficionado-admin/blob/master/src/directives/admin.js#L111

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
