### ISSUE TITLE
Is there an add-on that can collapse/expand a section/object/array area?

### ISSUE THREAD

**Issue by ricklxm** [json-schema-form/angular-schema-form#481]

**Comment by AlexAlbala** [comment]
+1

**Comment by rbro82** [comment]
This is the solution i came up with when i needed it:

I modeled this with a condition-option in the form definition like:

```javascript
{
              'type': 'fieldset',
              'title': 'Credit',
              'condition': 'model.some_boolean_value',
              'items': [
                {
                  'type': 'section', 'htmlClass': 'row', 'items': [
                  {
                    'type': 'section', 'htmlClass': 'col-md-3', 'items': [
                    {'type': 'help', 'helpvalue': '<label>Some Label<label>'}
                  ]
                  },
                  {
                    'type': 'section', 'htmlClass': 'col-md-2', 'items': [
                    {'key': 'some_other_key', 'type': 'checkbox', 'title': 'Yes', 'htmlClass': 'checkbox'}
                  ]
                  },
                  {
                    'type': 'section', 'htmlClass': 'col-md-7', 'items': [
                    {'key': 'another_key', 'type': 'textarea', 'notitle': true}
                  ]
                  }
                ]
                }
}
```


Where 'model.some_boolean_value' is some checkbox in my case, but u can use Angular expressions here so u can basically check for anything u need to. If said checkbox is checked the fieldset is shown otherwise it won't.
See the docs: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#standard-options
> condition: "person.age < 18" // Show or hide field depending on an angular expression

A different way could be to build custom css classes which could be managed by a directive.

Does anybody know another or easier solution?

Regards,
rbr

**Comment by nicklasb** [comment]
I don't know of any such add-on. However, you are obviously welcome to make a PR to this project, it could be a good thing to have a "hideable"-option with some little clickable symbol that collapses.

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
