### ISSUE TITLE
type is date ，  title is hiden

### ISSUE THREAD

**Issue by viyongyong** [json-schema-form/angular-schema-form#484]
hi,there,when i add a new input type is date and the title is null and not display.if there has something wrong?thank you.

**Comment by nicklasb** [comment]
I am sorry, but i am having problems understanding your problem.
Please try and see if you can recreate it in the example page, if so click on save to gist and add the link here.

**Comment by Anthropic** [comment]
@viyongyong please re-open when you can provide a gist/plunker/demo.

**Comment by chargrove** [comment]
I'm seeing the issue here and it is just that the title field doesn't show when putting in a "type":"date" for the schema.  This falls back to the default field template and the title doesn't actually show unless specified from the Form definition.

http://schemaform.io/examples/bootstrap-example.html#/66a572514f0363b77f3ef2a7bc40a8c5

They also reference this problem on issue 412.

**Comment by Anthropic** [comment]
Thanks @chargrove for finding a previous issue and providing example, appreciate it :)

**Comment by Anthropic** [comment]
The schema cannot be set to type: date, that is [not a valid json-schema type](http://json-schema.org/latest/json-schema-core.html), you can only set that in the form definition.

Here's a working example:
http://schemaform.io/examples/bootstrap-example.html#/7dbeb20f58be76c7609d6f304ba1083d
