### ISSUE TITLE
De-couple from Bootstrap [enhancement]

### ISSUE THREAD

**Issue by ryedin** [json-schema-form/angular-schema-form#506]
Man this would be really great if it wasn't dependent on bootstrap (or any particular UI framework). We should be able to have full control over that part (for example, use with https://material.angularjs.org/latest/#/)

Any plans to remove this tight coupling to bootstrap? It would make the library instantly more accessible and desirable to a larger number of projects.

**Comment by gazpachoking** [comment]
Decorators can be made for any ui framework in theory, bootstrap is just the included one. There is an (in progress) decorator for angular material here. https://github.com/Textalk/angular-schema-form-material
I'm also wanting to switch to that, haven't gotten a chance to try it out yet though, not sure how complete/usable it is at the moment.

**Comment by davidlgj** [comment]
@ryedin ASF has been designed with that in mind from the start, and as @gazpachoking said there is a Angular Material decorator in the works, but it's currently broken. The reason nothing has happened to it in a while is that we're working on a refactoring that needs to be done first, see https://medium.com/@SchemaFormIO/the-new-builder-pt-1-61fadde3c678

But the work on the new builder is going well, so soon the material decorator work can resume.

**Comment by davidlgj** [comment]
btw Angular Material is one of the harder to implement. Implementing a pure CSS framework should be pretty straightforward, basically just editing the templates. I've tinkered a bit with a Foundation decorator, but since we don't use Foundation I let it go. I'm going to write some docs on it soon.

**Comment by ryedin** [comment]
Awesome, glad to hear it!

angular-material >>> bootstrap, so can't wait! (ok... that's slightly opinionated, but oh well :))

**Comment by nicklasb** [comment]
Yes, material looks really nice. Wouldn't mind that at all.

**Comment by ryedin** [comment]
@davidlgj how is it going on the "new builder" and by extentsion, the material decorator. I see there have been some recent commits here, just curious as I am getting closer to the point of our project where I might want to pull this thing in. Of course, our app is material, so can only do this if there is a decently workable path for the material decorator. I'm happy to jump in there (potentially, if hours permit), but don't want to do that if you're about to drop a big "booyah" bomb and release the shiny new 100% working material decorator codebase on us all :)

**Comment by davidlgj** [comment]
Hi @ryedin! We'd love to get your help.

The new builder is up and running in the latest release, but not used by the the `dist/bootstrap-decorator.min.js` decorator. For the next release (that's not a hotfix) I will remove it. 

The new bootstrap decorator that uses the builder is fully functional and has it's home here: 
https://github.com/Textalk/angular-schema-form-bootstrap 

So you can say it's already released but a bit sneakily.

I have no bomb to drop :)  I've been concentrating on bugs and getting the bootstrap decorator up and running and so @Anthropic has been doing the latest work. (do you have a code bomb @Anthropic?)

So, the state of the material decorator is that it has a start with the most basic types, although not perfectly. It also has solutions for some of the integration points, like how to display validation messages. What needs to be done is to implement as many of the form types as possible, write tests (probably protractor) and document. 

Since its the decorator that decides what types are implemented and what options they support we probably want types for a lot of stuff that's material specific. I'd consider it release worthy if we at least have the types that are used as defaults for schemas. I.e. `text`, `number`, `integer`. `textarea`, `select`, `array`, `fieldset` (probably should correspond to something else) and `checkbox` (i believe thats all...)

To implement a form type one would first look at the corresponding type in the bootstrap decorator to get a good idea on how it should be done. Most types should be straight forward to migrate (array maybe the most complicated). 

If you start work on something consider doing a "work-in-progress" PR to let us know and to get early feedback.

**Comment by ryedin** [comment]
OK, cool. Thanks for the update.

I'll see what sort of time I can set aside for this. There are many things the proverbial plate (just like everyone else).

**Comment by Anthropic** [comment]
@ryedin I've just finished wrapping my head around the inner workings of @davidlgj 's new builder while upgrading a project I have at work. I like it much more, but like anything new, took a little getting used to. I think I am on top of it now so I will be doing some more work on the Material decorator soon. 

We have had to wait for Angular Material to get more stable too, when we first started on it, they kept making breaking changes since it is pre-1.0, so I slowed down a bit in frustration. But they are releasing 1.0 soon and I will do my best to get as much done on it as I can once that happens :)

**Comment by ryedin** [comment]
@Anthropic awesome new, man.

Yeah, it's definitely a challenge to be working on an integration project where both sides of the integration are moving targets!

Keep us posted. Like I said, I might be able to jump in at some point here, too... at least with some busy work once you've nailed down the correct implementation patterns.

**Comment by Anthropic** [comment]
@ryedin I added some more parts to it this weekend, I also started to add some issues in the ASFMaterial repo to keep track of things I want to add, but haven't yet. Feel free to add issues or contribute over there.

**Comment by ryedin** [comment]
@Anthropic cool. I'll try to check it out this week some time... Got like a 1.4 bazillion things on my plate I'm behind on right now :)

Thanks for the update. This is pretty exciting.

**Comment by jmls** [comment]
so what's the status of this new builder ? Is it part of the standard installation now ?

**Comment by nicklasb** [comment]
The core is currently being broken out into: https://github.com/json-schema-form/json-schema-form-core

**Comment by nicklasb** [comment]
Oh, I answered the wrong question, the *builder* is currently optional, it will likely be in the upcoming 1.0 release.

**Comment by ryedin** [comment]
AWESOME news! (total de-coupling FTW).

Is there a blog post or any other content around this direction that I can use to get up to speed (i.e. any and all related repos that have been spawned)? Still in the same time-starved situation, but would be good to at least keep tabs on this.

Thanks for the update btw.

**Comment by nicklasb** [comment]
Well, the core repo I mentioned above. The discussion is a loong one and is not only about that. I added you to the planning gitter room. 
But the diskussion is *supposed* to happen in the other one (json-schema-form/json-schema-form-projects).

**Comment by Anthropic** [comment]
This is part of 1.0.0 alpha using the agnostic core and the builder that can be used for Material decorator too. More work will go into it, but I think we can close this issue.
