### ISSUE TITLE
Highlight array tab, if form in tab is invalid

### ISSUE THREAD

**Issue by eburi** [json-schema-form/angular-schema-form#610]
I'm using ```"type":"tabarray"``` for an array and I'm looking for a way to put a css class on the ``<li>```-element of the tab if any field in that tab is invalid.

I wonder if there is an elegant way to do it. We've found an ugly hack we can do in our controller where we look into the ```form.$errors``` and then add that styling....

I added a custom mapping where I get the elements of the array as ```form.items``` and eventually pass these into a ```<bootstrap-decorator form="item"></bootstrap-decorator>``` that will render the form-fields. 

Given this extension-template:
```
<fieldset ng-disabled="form.readonly" class="schema-form-fieldset {{form.htmlClass}}">
    <label class="control-label" ng-class="{'sr-only': !showTitle() }">{{ form.title }}</label>
    <div ng-init="selected = { tab: 0 }" class="schema-form-translatable {{form.htmlClass}}">
        <ul class="nav nav-tabs">
            <li ng-repeat="item in form.items"
                ng-disabled="item.readonly"
                ng-click="$event.preventDefault() || (selected.tab = $index)"
                ng-class="{ active: selected.tab === $index }"
                class="has-error tab-required"
                    >
                <a ng-href="#" class="a-tag-required">{{ item.key.slice(-1)[0] | uppercase }}</a>
            </li>
        </ul>

        <div class="tab-content {{form.fieldHtmlClass}}">
            <div class="tab-pane"
                 ng-disabled="form.readonly"
                 ng-repeat="item in form.items"
                 ng-show="selected.tab === $index"
                 ng-class="{ active: selected.tab === $index }">
                <bootstrap-decorator form="item"></bootstrap-decorator>
            </div>
        </div>
    </div>
    <div class="help-block" ng-show="form.description" ng-bind-html="form.description"></div>
    {{ languages = $$value$$; ''}}
</fieldset>
```

Here I would like to put an additional expression into ```ng-class="{ active: selected.tab === $index }"``` but I can't figure out how to find out if just this sub-tree of the form is invalid:
```
<li ng-repeat="item in form.items"
     ng-disabled="item.readonly"
     ng-click="$event.preventDefault() || (selected.tab = $index)"
     ng-class="{ active: selected.tab === $index }"
     class="has-error tab-required"
>
    <a ng-href="#" class="a-tag-required">{{ item.key.slice(-1)[0] | uppercase }}</a>
</li>
```

**Comment by eburi** [comment]
I think this should actually be something that is built into schemaform for better usability. 

User fills out a form that has list wich uses the "tabarray". User wants to submit the form, but can't due to validation errors. If that error is inside a tab that is currently not active, it's not obvious to the user where the problem is.

Isn't that a very common thing? How to improve the usability?

**Comment by eburi** [comment]
This seems to be a duplicate of #336

**Comment by catchshyam** [comment]
The most elegant solution is to change the tabarray template to bring each tab content under form tag and then use the ngFormController to validate the tab contents. However, this would require you to write some code.

There is another dirty hack which will work if you have not disabled the debug info on DOM (using $compileProvider.debugInfoEnabled(window.whatif.enableAngularCompilerDebug)).

You can use a sample implementation like the following,

```
function validateTabArray(){
	var tabItemsGroup = $($elem).find('[schema-form-array-items]');

	_.forEach(tabItemsGroup, function (tabContents, index) {
		var itemsToValidate = $(tabContents).find('[schema-validate]'),

		var tabHasErrors = [];

		_.forEach(itemsToValidate, function (tabItem) {
			// schema-validate directive puts the ngModelController on scope as `ngModel`
			// from that we can get error codes
			var itemObj = $(tabItem),
				scope = itemObj.scope(),
				error;

			if (scope && scope.ngModel) {
				error = _.omit(scope.ngModel.$error, 'parse');
				if (_.keys(error)[0]) {
					tabHasErrors[index] = true;
				}else{
					tabHasErrors[index] = false;
				}
			}
			return tabHasErrors;
		});
	});
}
```

**Comment by Anthropic** [comment]
@eburi thank you for finding the duplicate, I appreciate it, I will close this issue, please feel free to add further comments to #336

@catchshyam thank you for your contribution, please comment on #336 or consider a pull request on the boostrap decorator repo https://github.com/json-schema-form/angular-schema-form-bootstrap

**Comment by ericxinzhang** [comment]
I had same requirement and worked out a quick solution. Note that the solution is 
- Not self-contained, you will have to expose some function in your model or service for the angular-schema-form directive to call.
- Not a ideal solution, but the changes required are relatively small. 

1. For tabarray, the angular-schema-form I'm using (v0.8.13) generates the input's ng-model attribute value as something like `model['users']['0']['userid']`, but generates the name attribute using the last part in ng-model value, in this case `userid`, and the only exceptional case is radiobuttons, in which case the name is `users.0.userid`. I updated all the templates, changed the name attribute to `name="{{form.key.join('.')}}"`, which joins all form.key by '.'

2. I then created a service which called in ng-submit, parses the form.$error object and stores the errors by tab index, then by input name.

3. As the angular-schema-form diretives have isolated scope and cannot access controller's scope, I added a function hasError() to the model (which is passed to directive by sf-model). This function calls the service and return true if a tab has eror given the tab index.

4. Finally I updated the template to add in the ng-class to the tab: `ng-class="{'validation-error':  model.hasError($index)}"`

**Comment by raquintero** [comment]
@ericxinzhang Your solution sounds great!  Do you have a plunker or demo somewhere showing your updates?
I am in the process of extending all the bootstrap-decorators so I can add `i18n` support and add unique ID's to all field elements.  The transformation of the Form object using Objectpath has gotten in my way and was forced to hack around it, which forced me to create a "dirty" model, then post-process it to get to my desired output.

**Comment by ericxinzhang** [comment]
@raquintero I don't have a plunker to show my updates at the moment. Will extract the changes from my project and create one when I have time, hopefully by this weekend.

**Comment by raquintero** [comment]
@ericxinzhang That would be awesome if you could find the time!

**Comment by ericxinzhang** [comment]
@raquintero  here you go http://plnkr.co/edit/pk4YzPlFBcjk26zr1hbY?p=preview

**Comment by raquintero** [comment]
@ericxinzhang Hey man, I forgot to say thanks!!!!

**Comment by AndrewIsh** [comment]
I am in the middle of creating what I hope will end up being a PR for this, based on the excellent work done by @ericxinzhang. I was a bit uneasy with modifying the way the name attribute is formed, partly because I wasn't sure of the implications this might have elsewhere, but also because there are plans afoot to alter it in #683.

In an attempt to avoid this, I created a custom builder called `sfContext` which I was intending storing the field's larger context (including tab). This all worked fine, however I ran into a brick wall when it came to passing that context to the `$error` object (for subsequent parsing when creating the ErrorService object). I couldn't see any way of getting the context from the field's `sf-context` attribute into the `$error` object, or into anything else that could be accessed via the ErrorService for that matter. So, in the end, I've returned to modifying the name attribute, since that *is* passed to the `$error` object.

I'll update here if and when I have a PR ready!

**Comment by AndrewIsh** [comment]
Once I spent some time looking at this it became clear that it wasn't going to be as straightforward as I'd hoped.

The fundamental problem I've hit is that my application is using a `tabs` form type, whereas the solution proposed by @ericxinzhang is using a `tabarray`. Looking into it, is seems that these two form types are built in fundamentally different ways, the practical upshot of this is that fields within the `tabs` form have no context about where they are in the larger picture, which is surfaced within the `name` attribute on the individual controls. Given that @ericxinzhang's solution hinges on this, I'm at a bit of a dead end. 

I've spent longer than I care to admit trying to figure out the nuances of the build process in order to see how I could replicate the relevant bits of the path building for `tabs` form types, but there are so many moving parts I'm finding it extremely difficult to get a feel for what's happening.

If anyone is able to shed any light on this, it would be gratefully received. I guess I'd really like to know:
- a) Is it really as big an undertaking as it appears to be?
- b) I'm thinking I'd have to create a `tabs` directive and, within that, somehow traverse each tab and then the contents of each tab giving it context about the enclosing tab, does that sound reasonable?
- c) Any other advice would be gratefully received.

I'm keen to stick to the proposed solution as it seems to be straightforward, I'm just struggling with how to get the necessary context into `tabs`.

Thanks!

**Comment by Anthropic** [comment]
@AndrewIsh it is complex, taken me a long time to get up to speed on it, I haven't spent too much time on it for tabs, but I would expect that there needs to be ng-form added to catch the status of the form element children.

**Comment by Anthropic** [comment]
@AndrewIsh this should probably be a new issue regarding tabs showing status as they are quite separate. Then we can discuss it there.

**Comment by ericxinzhang** [comment]
Hello guys, highlighting the tab with errors is easy if jQuery is available. Please check out this example http://plnkr.co/edit/8TFFM0r3HPLrGP5HmqQA?p=preview, in which the highlightTabs() function add error number as badge after the tab label, and works for both tabs and tabarray. This function was actually created by my colleague.

If I had time, I probably would create a directive which will do the same thing as highlightTabs() and add it to the schemaform template for tabs & tabarray so that the tab highlighting is done when schemaFormValidate event is broadcasted. Also evening without jQuery included, the element parameter provided by angularjs is actually a mini version of jQuery element object, which probably is able to do the same.

**Comment by AndrewIsh** [comment]
Hi @ericxinzhang 

Interesting. That certainly does work. My immediate feeling is that it doesn't feel particularly 'angular', it's more about adding UI sparkle based on the presence of classes adding following validation. While this is a valid approach, it feels cleaner for us to be basing our evaluation of whether a tab's pane contains invalid fields on the form object's `$error` property rather than whether the markup contains particular classes. That said, I'm very much a newcomer to this project, so I may well be talking complete rubbish (and will happily be told so!).

Anyway, this is a *very* good short term solution (which I'm in desperate need of), so will likely implement this as a fix whilst the discussion of how a long term fix should look continues. So thanks very much for posting it! :+1: 

Many thanks
Andrew

**Comment by ericxinzhang** [comment]
Hi @AndrewIsh,

You are absolutely right, with angular we should minimize DOM manipulating. The solution is really a quick and short term one :-) but I'm glad it helps

**Comment by AndrewIsh** [comment]
@ericxinzhang Just to update, I implemented this and it's working nicely. Many thanks for your suggestion, much appreciated :)
