### ISSUE TITLE
How to add input field inside label 

### ISSUE THREAD

**Issue by anjum121** [json-schema-form/angular-schema-form#636]
Exploring this great library, I search on google/docs/issues but couldn't find an example which shows label wrapped around input file,

Current result 

`<label class="item"></label> <input  type="text" />`

Expected outcome 
`<label class="item item-input item-stacked-label">
  <span class="input-label">First Name</span>
  <input type="text" placeholder="John">
</label>`

**Comment by Anthropic** [comment]
@anjum121 The label tag does not need to parent an input so that is not an expected outcome. However there are enhancements requested and a PR around more unique names for fields, but you are also free to change the template to suit your needs by copying the decorator and making your own.

Please re-open if you do not feel the question is answered sufficiently.
