### ISSUE TITLE
Nested schema properties key shared in form object

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#683]
#### Plunker

[Example](https://plnkr.co/edit/Lxfrd0?p=preview)

When using a schema with nested properties, where the nested property shares the same name as another nested property (see the 'raw' property in the example), the form object (as logged to the console in the example) seems to only contain a single property, for the final nested property with that name. It appears the form control property is being overwritten with each occurrence of one with that name.

I would expect the form object to contain a property for each parent schema property with the nested property as a child, in the example:

```
{
  [...form validity etc...]
  year: {
    raw: [...form element validity etc...]
  },
  month: {
    raw: [...form element validity etc...]
  }
}
```

instead, I see:

```
{
  [...form validity etc...]
  raw: [...form element validity etc...]
}
```

This is causing me problems because I am unable to access the discrete validity etc. of each form control.

I'm sure I must be misunderstanding how ASF works in this regard. If anyone is able to shed any light on this, I'd be very grateful :)

**Comment by mrenvoize** [comment]
:+1:   This is an annoying bug that I can replicate.. no idea where to fix though :(

**Comment by Anthropic** [comment]
@AndrewIsh @mrenvoize this is a known behaviour and is because of the way forms take the name property of the field, I made a fix for the Material decorator I work on, but no-one has ported it to the bootstrap decorator.

If you look at https://github.com/json-schema-form/angular-schema-form-material/blob/develop/src/default.html you can see that instead of using {{form.key.slice(-1)[0]}} taking only the last part of the key like the bootstrap decorator does I used a filter {{::form.key|sfCamelKey}} to convert your case to yearRaw. That filer is in the material-decorator file and would also need to be added to bootstrap decorator.

If either of you have the time to update the templates and make a PR it would be greatly appreciated!

**Comment by Anthropic** [comment]
It would need any id,for,name to be updated also.

**Comment by kyse** [comment]
I'll probably tackle this soon, I'm experiencing the same issues with my getterSetter builder reusing the same object property for an array.  I've also been meaning to update those templates to wrap inputs in div's with an ng-class so one can easily set input widths via col-xs-# when using form-horizontal.

**Comment by kyse** [comment]
So the method you used with sfCamelKey works well.  But for my case I am using a getterSetter builder to allow more control over the input value to model binding and arrays in the schema while not using the array controls.  Because this results in part of the key being undefined or null (the array index), I had to resort to baking in some logic to handle that situation.  Ie, store the key being parsed, if it already exists and has been added to a control template, return key + i++ (ie key1, key2).  So not sure this would work out as a PR for the bootstrap decorator.

**Comment by Anthropic** [comment]
Thanks for the update @kyse, I am working on updating the decorators, time consuming, but I have some time off soon :)

**Comment by AndrewIsh** [comment]
Is there any progress with this. I'm currently working on creating a PR for #610, part of which is altering the name attribute formation from `form.key.slice(-1)[0]` to `form.key.join('.')` so if there are ongoing alternative plans for the formation of this attribute, I'd be better off using that. I like the idea of using `sfCamelKey` but it seems that the use case @kyse mentioned might be problematic for that?

**Comment by Anthropic** [comment]
@AndrewIsh yes I have updated the way keys and ids are generated in the webpack branch, talk to me in gitter PM and I will fill you in on where changes are happening.

**Comment by Anthropic** [comment]
This should be working now in the alphas, please re-open if there's still issues.
