### ISSUE TITLE
Embedding to a .net project

### ISSUE THREAD

**Issue by joseg** [json-schema-form/angular-schema-form#704]
#### Enhancement
Could you include steps to embed angular-schema-form into a .net angular project?

**Comment by Anthropic** [comment]
@joseg not sure what you mean, are you referring to intellisense in Visual Studio or something else? As far as I know, you include it the same way and there's nothing special for .net to care about as far as I know other than intellisense, you can just grab the bower version and put that in a folder in your .net solution.

I haven't used .net since node came out so I don't know what new stuff they have so I could be wrong but without more information I can't be much help.

**Comment by Anthropic** [comment]
Please re-open if you can provide more information :)
