### ISSUE TITLE
How to add a custom builder with dependencies

### ISSUE THREAD

**Issue by divercraig** [json-schema-form/angular-schema-form#790]
I expected to be able to add my own builder functions to my addOn and have it used by angular-schema-form but it seems that the builder can only access providers which do not support dependencies on other services.

If I want to define an addOn with a custom builder I configure the schemaFormDecoratorsProvider

```
angular.module("schemaForm")
    .config(["schemaFormDecoratorsProvider", "schemaFormProvider", "sfPathProvider", "sfBuilderProvider", "customBuilderProvider",
        function(schemaFormDecoratorsProvider, schemaFormProvider, sfPathProvider, sfBuilderProvider, customBuilderProvider) {
            var ngModelOptions = sfBuilderProvider.builders.ngModelOptions;
            var ngModel = sfBuilderProvider.builders.ngModel;
            var sfField = sfBuilderProvider.builders.sfField;
            var condition = sfBuilderProvider.builders.condition;
            var customBuilder = customBuilderProvider.builder;

           schemaFormDecoratorsProvider.defineAddOn("customTypeDecorator", "custom-type", "custom-type-decorator.html",  [sfField, ngModel, ngModelOptions, condition, customBuilder]);
        }
    ]);
```

This new custom-type needs a custom builder to add support functions to the form, because this custom builder is being used in a config it needs to be part of a provider. In my example below the builder is simply using a service to add some new property to the form object which can be used in the decorator template.

```
angular.module("schemaForm")
    .provider("customBuilder", function customBuilderProvider() {
        this.$get = ["randomGeneratorService", function(randomGeneratorService) {
                return {
                    builder: function(args) {
                         args.form.randonNumber = randomGeneratorService.generate();
                    }
                };
            }];
        }
    );
```

The provider's `$get` function returns an object containing the builder function. It also has a dependency on a service - which is not available at config time.

The problem I'm experiencing is that the configuration of schemaFormDecoratorsProvider only uses my `customBuilderProvider` not the `customerBuilder` itself. This means the builder hasn't been defined yet and causes an error. I can't just add the function to the provider because it has dependencies on services which aren't available at config time.

Is there a way to add a custom builder for an add-on which actually users an angular Service rather than a Provider?

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@divercraig have you tried adding a function below where you have ```var seating``` (doesn't this line cause an error?) that then calls the service?

To be honest I have all my builders only act based on what is in the form data so I haven't got anything calling a service so I have not tried to see which format it needs to be. I would have thought it would be reasonably straight forward though. If you make a plunker I can take a look at helping further.

**Comment by divercraig** [comment]
Hey @Anthropic,

apologies about that extra line. I left in in from my actual code while I was trying to sanitise my example. I'll get that plunker up shortly for you.

**Comment by divercraig** [comment]
Hey @Anthropic, I've got a plunker at https://plnkr.co/edit/qcbP0uiScV78WB5bLr8W?p=preview If you open the console you'll see that an error us called because the builder function isn't available. This is because the $get function is not called.

Regards,
Craig

**Comment by kyse** [comment]
I know this is a few months old, but if you haven't gotten this taken care of yet:

Schema Form wants a function for the builder, because the loop will treat it as a function and try and pass it some params.

For some reason, even though the builder is being called from outside the config phase, the injector refuses to return anything other than Providers.  So doing some trickery with passing (provider-type) $injector into a wrapper that injects the real $injector isn't working so well.

```
var customBuilder = $injector.invoke.bind(null, ['$injector', function wrapper($injector2) {
  $injector2.invoke(customBuilderProvider.$get).builder(this);
}
```

While it should work, it doesn't.  Still complains about the generatorService 'provider' not being found.  This boggles me actually, I obviously don't understand something. :)

So, two options:
If you absolutely must have a provider because you need to do some config setup of the provider, then you need to use some $injector trickery to grab your generator service inside the provider's $get method so it will work in normal circumstances, where your injecting customBuilder, and for when you need to grab it from injecting customBuilderProvider.

Or, just define a factory, and inject the factory, inject customBuilderFactoryProvider into the decorator config block.  Set your builder to customBuilderFactoryProvider.get().builder.  Injection for the service works properly in this case.

Example for both cases: https://plnkr.co/MBapT9

Or beg the schema-form folks to actually update their library to run $injector.invoke(buildFn).  But frankly, this would probably cause a performance impact on large field forms I'm not sure is desirable.

Finally, maybe I'm off my rocker here, but I think you might have ended up with a dependency issue trying to have your provider in the schemaForm module rather than your myApp module where your service was defined.  Not sure if the $injector service would play ball with that.  There's really no need to define your decorators under the schemaForm module unless your overwriting stock functionality in the bootstrapDecorator I wouldn't think?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently, I'm spring cleaning quiet issues.
