### ISSUE TITLE
Radio buttons do not store boolean values in array

### ISSUE THREAD

**Issue by ivarprudnikov** [json-schema-form/angular-schema-form#852]
#### Radio buttons do not store value

Documentation contains example of radio buttons with titleMap that binds to boolean schema field and it works unless those radio buttons are in Array.

#### Dependency versions

- angular 1.5.11
- angular-sanitize 1.5.11
- angular-schema-form 0.8.13
- jquery 1.9.1
- ObjectPath 1.1.0 (bower version)
- TV4 1.2.7 (bower version)

#### Gist/Plunker/Demo
[Plunker example showing the issue](https://plnkr.co/edit/I8Fs1r)

#### Related issues
This is/maybe related to:
- https://github.com/json-schema-form/angular-schema-form/issues/330 Checkbox inside an array for more than one level doesn't work #330 
- https://github.com/json-schema-form/angular-schema-form/issues/274 Deleting array item in multi-item array copies deleted invalid value to another array item #274

@json-schema-form/angular-schema-form-lead

**Comment by vinhthang** [comment]
I tried your example with schemaform.io example and it worked

http://schemaform.io/examples/bootstrap-example.html#/b253cb6f17d61e46eee2bbfe448b63d7

maybe you should change to 1.0 alpha

**Comment by Anthropic** [comment]
@ivarprudnikov @vinhthang this was an issue introduced by the new builder, it should be fixed within the alpha, but there are some issues still with add-ons, so if you aren't using any add-ons then you should be fine to go with the alpha now. Otherwise you may have to downgrade to 0.8.12 which I think is what the schemaform.io demo is using.

**Comment by Anthropic** [comment]
@john-latham is this one of the issues you have been having?

**Comment by Anthropic** [comment]
This should be working again in the latest alpha.

**Comment by ivarprudnikov** [comment]
Updated plunker showing that it works in `1.0.0-alpha.4` https://plnkr.co/edit/vnyh4yWedQR7UD21yCI4?p=preview

**Comment by ivarprudnikov** [comment]
@Anthropic could you point to the code which fixes the issue in `1.0.0-alpha.4` so that fix can be backported to `0.8` branch?

**Comment by Anthropic** [comment]
@ivarprudnikov that's a bit tricky, I expect that it is related to a combination of the field names, which now use a function to ensure that ids and names are unique and also that arrays now manage themselves using $$hashKey instead of $index. I never specifically fixed this issue, I just fixed so many array based issues it got lucky :)

The changelog should list all the issues and hopefully the commit either had the code in it or was within one or two commits that did. Sorry but that's the best I can offer for now.
